# Generated by Django 4.2.1 on 2023-05-07 18:20

import chat_merger_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "api_token",
                    models.CharField(default=chat_merger_utils.generate_secret, max_length=255, unique=True),
                ),
            ],
            options={
                "verbose_name": "🤖 Bot",
                "verbose_name_plural": "🤖 Bots",
            },
        ),
    ]
